In [ ]:
i_lis =  [1,2,3,4]
s_lis = ['milk', 'egg', 'butter']

In [ ]:
print(s_lis[1])

egg


In [ ]:
def travers(data):
    for i in data:
        print(i)

In [ ]:
travers(s_lis)

milk
egg
butter


IndexError: list index out of range

In [ ]:
for i in range(len(s_lis)):
    s_lis[i] = s_lis[i]+"test"

In [ ]:
s_lis

['milktest', 'eggtest', 'buttertest']

In [ ]:
my_list = list(range(5))

In [ ]:
my_list

[0, 1, 2, 3, 4]

In [ ]:
my_list[2]=23

In [ ]:
my_list.append(2345)

In [ ]:
my_list

[0, 1, 23, 3, 4, 2345]

In [ ]:
new_list= list(range(45,36,-3))

In [ ]:
my_list.extend(new_list)

In [ ]:
my_list

[0, 1, 23, 3, 4, 2345, 45, 42, 39]

In [ ]:
my_list  = ['a', 'b', 'c', 'd', 'e']


In [ ]:
my_list[:2]

['a', 'b']

In [ ]:
my_list.pop(3)

'd'

In [ ]:
del my_list[2]

In [ ]:
my_list

['a', 'b']

In [ ]:
my_list.append('d')

In [ ]:
my_list.remove('a')

In [ ]:
my_list

['b', 'd', 'd']

In [ ]:
my_list = list(range(10,100,10))

In [ ]:
def check_value(list, target):
    if target in list:
        print(f"{target} found on the list")
    else:
        print(f"{target} not on the list")

In [ ]:
check_value(my_list, 20)

20 found on the list


In [ ]:
def linear_search(list, target):
    for i, value in enumerate(list):
        if value == target:
            return i
    return -1

In [ ]:
a =[1,2,3,4]
b =[5,6,7,8]

In [ ]:
a+b

[1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
a*4

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
list(map((lambda a: a*4),a))

[4, 8, 12, 16]

In [ ]:
list(filter((lambda a: a*4 >10), a))

[3, 4]

In [ ]:
len(a)

4

In [ ]:
max(a)

4

In [ ]:
min(a)

1

In [ ]:
sum(a)

10

In [ ]:
avg = (min(a)+max(a))/len(a)

In [ ]:
avg

1.25

In [ ]:
sum(a)/len(a)

2.5

In [ ]:
total = 0
count = 0
while True:
    num = input("Enter number: ")
    if  num == "done": break
    total += float(num)
    count += 1
    
avg = total/count    
print(avg)

10.0


In [ ]:
a = "spam-spam"
b = list(a)

In [ ]:
delemeter = '-'
a.split('-')

['spam', 'spam']

In [ ]:
delemeter.join(b)

's-p-a-m---s-p-a-m'

In [ ]:
a = [2,5,74.,5,7]

In [ ]:
a.remove(74)

In [ ]:
a = a + [10]

In [ ]:
a

[2, 5, 5, 7, 10, [45]]

In [ ]:
a.append([45])

In [ ]:
a

[2, 5, 5, 7, 10, [45]]

In [ ]:
ori = a[:]

In [ ]:

ori.sort()

In [ ]:
ori

[2, 5, 5, 7, 74.0]

In [ ]:
a

[2, 5, 74.0, 5, 7]

In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([1,2,3,4,5])
alist = [1,2,3,4,5]

In [ ]:

arr1/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [ ]:
alist/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [ ]:
a

[2, 5, 74.0, 5, 7]

In [ ]:
c = [a*2 for a in a]

In [ ]:
c

[4, 10, 148.0, 10, 14]

In [ ]:
language = "Python"
new_list = [l for l in language]

In [ ]:
new_list

['P', 'y', 't', 'h', 'o', 'n']

In [ ]:
list(language)

['P', 'y', 't', 'h', 'o', 'n']

In [ ]:
prev = [-5,1,-4,7,-2,6,-89,90]

In [ ]:
list(filter((lambda a: a*2 < 0),prev))


[-5, -4, -2, -89]

In [ ]:
[number**2 for number in prev if number < 0]

[25, 16, 4, 7921]

In [ ]:
sentance = "my name is dilan"
vouvels = ['a', 'e', 'i', 'o', 'u']



In [ ]:
[c.upper() for c in sentance if c.lower() not in vouvels]

['M', 'Y', ' ', 'N', 'M', ' ', 'S', ' ', 'D', 'L', 'N']

In [ ]:
def aw(num):
    return num*10
def bw(num):
    return num if num<0 else num*8

In [ ]:
prev

[-5, 1, -4, 7, -2, 6, -89, 90]

In [ ]:
[aw(a) if a > 0 else bw(a) for a in prev]

[-0.5555555555555556,
 10,
 -0.4444444444444444,
 70,
 -0.2222222222222222,
 60,
 -9.88888888888889,
 900]

In [ ]:
a = [1,3,-56,56,-85,23,78]


def na(n):
    return n*-2 if n<0 else n**-2
def nb(n):
    return n**3 if n>0 else n**9


In [ ]:
[na(n) if n<0 else nb(n) for n in a]

[1, 27, 112, 175616, 170, 12167, 474552]

In [ ]:
import random

In [ ]:
random.shuffle(a)

In [ ]:
a

[56, -85, 78, 23, 1, 3, -56]

In [ ]:
while True:
    num_days = input("Hom many day's tempreature: ")
    if num_days == "done": break
    daily_temp = []
    
    for i in range(int(num_days)):
        temp = float(input(f"Enter day {i} tempreture: "))
        daily_temp.append(temp)
        
    average = sum(daily_temp)/len(daily_temp)
    
    days_above_avg = len([t for t in daily_temp if t > average] )
    print(f'Average tempreture is: {average} ')
    print(f'Days above average tempreture: {days_above_avg}')
    
    
    

In [ ]:
import array

In [ ]:
a = array.array('i', range(6))

In [ ]:
sorted(a)


[0, 1, 2, 3, 4, 5]

In [ ]:
def missing_number(arr, n):
    sum_of_original = sum(arr)
    expected_sum = n*(n+1)//2
    print(f"sum of original {sum_of_original}")
    print(f"expected sum {expected_sum}") 

missing_number([1, 2, 3, 4, 6], 6)

sum of original 16
expected sum 21


In [ ]:
sum(range(1,6))

15

In [ ]:
sum(range(1,7))

21

In [ ]:
def two_sum(array, target):
    copy = array[:]
    for i in range(len(array)):
        for j in range(0+i,len(copy)):
            if (copy[i] + copy[j]) == 9: 
                print(i,j)
        
    
    
    

two_sum([2,7,11,15, -2], 9)

0 1
2 4


In [ ]:
ls = [1,2,3,4]

In [ ]:
ls.pop(0)

1

In [ ]:
ls

[2, 3, 4]

In [ ]:
a = np.arange(1,15)

In [ ]:
a[7] = 555

In [ ]:
a

array([  1,   2,   3,   4,   5,   6,   7, 555,   9,  10,  11,  12,  13,
        14])

In [ ]:
7 in a

True

In [ ]:
for i in a:
    if i == 7:
        print("Found")


Found


In [ ]:
def max_product(arr):
    # TODO
    max_product = 0
    n1,n2 = 0,0
    for i in range(len(arr)):
        for j in range(0+i, len(arr)):
            if i == j:
                continue
            product = arr[i]*arr[j]
            if product > max_product:
                max_product = product
                n1,n2 = i,j
    print(f"Output: {max_product} ({arr[n2]}*{arr[n1]})")

In [ ]:
arr = [1, 7, 3, 4, 9, 5] 
max_product(arr)

Output: 63 (9*7)


In [ ]:
myList2D= [[1,2,3],[4,5,6],[7,8,9]] 

In [ ]:
myList2D

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
len(myList2D)

3

In [ ]:
myList = [84,85,86,87,85,90,85,83,23,45,84,1,2,0]


In [ ]:
sorted(myList)[-2:]

[87, 90]

In [ ]:
myList.remove(90)

In [ ]:
sorted(myList,reverse=True)[:2]

[90, 87]

In [ ]:
m =[1, 1, 2, 2, 3, 4, 5]

In [ ]:
set(m)

{1, 2, 3, 4, 5}

In [ ]:
test = []

In [ ]:
's' in test

False

In [ ]:
def remove_duplicates(arr):
    # TODO
    uniq = []
    
    for i in arr:
        print(i)
        if i not in uniq:
            uniq.append(i)
    
    return uniq


In [ ]:
remove_duplicates([1, 1, 2, 2, 3, 4, 5])

1
1
2
2
3
4
5


[1, 2, 3, 4, 5]

In [ ]:
def pair_sum(myList, sum):
    # TODO
    list_size =  len(myList)
    target = 0
    v1,v2 = 0,0
    value_pairs = []
    
    for i in range(list_size):
        for j in range(i, list_size):
            if myList[i] + myList[j] == sum:
                value_pairs.append(f"{myList[i]}+{myList[j]}")
    return value_pairs

In [ ]:
pair_sum([2, 4, 3, 5, 6, -2, 4, 7, 8, 9],7)


['2+5', '4+3', '3+4', '-2+9']

In [ ]:
def permuations(list1, list2):
    if len(list1) != len(list2):
        print("test")
        return False
    count = 0
    for i in list1:
        if i in list2:
            count += 1
    return True if count == len(list1) else False

In [ ]:
permuations(['d','l', 'l','a'], ['a', 'i', 'i', 'd'])

False

In [ ]:
a = np.array([ 1, 2])
b =np.array([ 1, 2])

In [ ]:
a - b

array([0, 0])

In [ ]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
def rotate(matrix):
    rotate = matrix.copy()
    print(rotate)
    depth = len(matrix[0])
    width =  len(matrix)
    for i in range(width):
        for j in range(depth):
            rotate[i][3-j]=matrix[i][j]
            
    print(rotate)


In [ ]:
rotate(matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


IndexError: list assignment index out of range

In [ ]:
len(matrix[0])

3

In [ ]:
data = np.array(matrix)

In [ ]:
data.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])