In [1]:
import numpy as np

In [2]:
twoDArray = np.array([[11,15,10,6], [10,14,11,5], [12, 17, 12, 8],[15, 18, 14, 9]])

In [3]:

print(twoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


In [ ]:
twoDArray[1][0]

# time complexity is O nn
# space complexity is o nm

np.int64(10)

In [7]:
twoDArray.shape

(4, 4)

In [11]:
r1 = [2,3,6, 56]

In [13]:
new2da = np.insert(twoDArray, 0, [r1], axis=1)

In [24]:
new2da

array([[ 2, 11, 15, 10,  6],
       [ 3, 10, 14, 11,  5],
       [ 6, 12, 17, 12,  8],
       [56, 15, 18, 14,  9]])

In [23]:
new2da.shape

(4, 5)

In [20]:
new2da[2:][1:4:2]

array([[56, 15, 18, 14,  9]])

In [ ]:

def access_element(array, row_index, col_index):
    r, c = array.shape
    if (row_index >= r) and (col_index >=  c):
        print("index are out of bound")
        return 0
    else:
        return array[row_index][col_index]

In [26]:
print(access_element(new2da, 1, 4))

5


In [37]:
def traverse(array):
    r, c = array.shape
    for i in range(r):
        for j in range(c):
            print(array[i][j])

In [39]:
traverse(new2da)

2
11
15
10
6
3
10
14
11
5
6
12
17
12
8
56
15
18
14
9


In [48]:
def search_array(array, value):
    r,c = array.shape
    for i in range(r):
        for j in range(c):
            if not array[i][j] == value:
                continue
            else:
                print(f'item found at {i}:{j}')
                return 0

In [49]:

search_array(new2da,10)

item found at 0:3


0

In [50]:
new2da

array([[ 2, 11, 15, 10,  6],
       [ 3, 10, 14, 11,  5],
       [ 6, 12, 17, 12,  8],
       [56, 15, 18, 14,  9]])

In [51]:
np.delete(new2da, 1, axis=0)

array([[ 2, 11, 15, 10,  6],
       [ 6, 12, 17, 12,  8],
       [56, 15, 18, 14,  9]])

In [52]:
new2da

array([[ 2, 11, 15, 10,  6],
       [ 3, 10, 14, 11,  5],
       [ 6, 12, 17, 12,  8],
       [56, 15, 18, 14,  9]])